/**
 * Generates public/icons.svg (an SVG sprite) from the Font Awesome Free SVG set.
 * Only the icons listed in ICONS are included, so no icon font has to be shipped.
 *
 * Usage: npm run icons
 * Icons: Font Awesome Free by Fonticons, Inc. - CC BY 4.0 (https://fontawesome.com/license/free)
 */
import { readFile, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';

const require = createRequire(import.meta.url);
const faRoot = dirname(require.resolve('@fortawesome/fontawesome-free/package.json'));

/** sprite id -> [style folder, font awesome file name] */
const ICONS = {
  python: ['brands', 'python'],
  github: ['brands', 'github'],
  paypal: ['brands', 'paypal'],
  linkedin: ['brands', 'linkedin'],
  instagram: ['brands', 'instagram'],
  code: ['solid', 'code'],
  cube: ['solid', 'cube'],
  print: ['solid', 'print'],
  microchip: ['solid', 'microchip'],
  globe: ['solid', 'globe'],
  moon: ['solid', 'moon'],
  sun: ['solid', 'sun'],
  download: ['solid', 'file-arrow-down'],
  'chevron-down': ['solid', 'chevron-down'],
  'chevron-left': ['solid', 'chevron-left'],
  'chevron-right': ['solid', 'chevron-right'],
  ruler: ['solid', 'ruler-combined'],
  sync: ['solid', 'arrows-rotate'],
  compass: ['solid', 'drafting-compass'],
  helmet: ['solid', 'helmet-safety'],
  gear: ['solid', 'gear'],
  envelope: ['solid', 'envelope'],
  close: ['solid', 'xmark'],
};

const symbols = [];
for (const [id, [style, file]] of Object.entries(ICONS)) {
  const svg = await readFile(join(faRoot, 'svgs', style, `${file}.svg`), 'utf8');
  const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1];
  const paths = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map(([, d]) => d);
  if (!viewBox || paths.length === 0) throw new Error(`Cannot parse icon "${file}"`);
  const body = paths.map((d) => `<path d="${d}"/>`).join('');
  symbols.push(`  <symbol id="${id}" viewBox="${viewBox}" fill="currentColor">${body}</symbol>`);
}

const output = `<svg xmlns="http://www.w3.org/2000/svg">
  <!-- Generated by scripts/build-icons.mjs - do not edit by hand.
       Font Awesome Free by Fonticons, Inc. - Icons: CC BY 4.0 - https://fontawesome.com/license/free -->
${symbols.join('\n')}
</svg>
`;

await writeFile(new URL('../public/icons.svg', import.meta.url), output);
console.log(`Wrote public/icons.svg with ${symbols.length} icons`);
