/**
 * Generates the SVG icon sprite (src/assets/icons.svg) and the typed list of icon names
 * (src/components/ui/icon-names.ts) from:
 *   - Lucide (line icons, ISC license)           https://lucide.dev
 *   - Simple Icons (brand logos, CC0 license)    https://simpleicons.org
 *
 * Only the icons listed below are included, so the sprite stays tiny.
 * Usage: npm run icons
 */
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const lucideIcons = fileURLToPath(new URL('../node_modules/lucide-static/icons/', import.meta.url));
const simpleIcons = fileURLToPath(new URL('../node_modules/simple-icons/icons/', import.meta.url));

/** Sprite id -> Lucide icon file name (stroke icons). */
const LUCIDE = {
  'arrow-down': 'arrow-down',
  'arrow-left': 'arrow-left',
  'arrow-right': 'arrow-right',
  'arrow-up-right': 'arrow-up-right',
  check: 'check',
  'chevron-left': 'chevron-left',
  'chevron-right': 'chevron-right',
  compass: 'drafting-compass',
  cpu: 'cpu',
  cube: 'box',
  download: 'download',
  gear: 'settings',
  gift: 'gift',
  hardhat: 'hard-hat',
  image: 'image',
  languages: 'languages',
  layers: 'layers',
  mail: 'mail',
  menu: 'menu',
  moon: 'moon',
  play: 'play',
  printer: 'printer',
  refresh: 'refresh-cw',
  rotate3d: 'rotate-3d',
  ruler: 'ruler',
  send: 'send',
  sparkles: 'sparkles',
  sun: 'sun',
  terminal: 'square-terminal',
  x: 'x',
  zap: 'zap',
};

/** Sprite id (prefixed with `brand-`) -> Simple Icons slug (filled logos). */
const BRANDS = {
  github: 'github',
  instagram: 'instagram',
  paypal: 'paypal',
  python: 'python',
};

const symbols = [];
const names = [];

for (const [id, file] of Object.entries(LUCIDE)) {
  const svg = await readFile(lucideIcons + `${file}.svg`, 'utf8');
  const inner = svg
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/^[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .replace(/\s*\n\s*/g, '')
    .trim();
  if (!inner) throw new Error(`Cannot parse Lucide icon "${file}"`);
  symbols.push(`<symbol id="${id}" viewBox="0 0 24 24">${inner}</symbol>`);
  names.push(id);
}

for (const [id, slug] of Object.entries(BRANDS)) {
  const svg = await readFile(simpleIcons + `${slug}.svg`, 'utf8');
  const path = svg.match(/<path d="([^"]+)"/)?.[1];
  if (!path) throw new Error(`Cannot parse Simple Icons logo "${slug}"`);
  symbols.push(`<symbol id="brand-${id}" viewBox="0 0 24 24"><path d="${path}"/></symbol>`);
  names.push(`brand-${id}`);
}

const sprite = `<svg xmlns="http://www.w3.org/2000/svg">
<!-- Generated by scripts/build-icons.mjs - do not edit by hand.
     Lucide (ISC License) - https://lucide.dev/license
     Simple Icons (CC0 1.0) - https://github.com/simple-icons/simple-icons -->
${symbols.join('\n')}
</svg>
`;

const types = `// Generated by scripts/build-icons.mjs - do not edit by hand.
export const ICON_NAMES = [
${names.map((name) => `  '${name}',`).join('\n')}
] as const;

export type IconName = (typeof ICON_NAMES)[number];
`;

await writeFile(new URL('../src/assets/icons.svg', import.meta.url), sprite);
await writeFile(new URL('../src/components/ui/icon-names.ts', import.meta.url), types);
console.log(`Wrote src/assets/icons.svg (${names.length} icons, ${sprite.length} bytes)`);
